### ISSUE TITLE
Enable incremental build with Gradle build server to support hot code replace

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-gradle#1449]
Opening a Gradle project with a Gradle build server currently results in the loss of the hot reload feature. This is because the build server does not support auto build and the Java debugger has no way to obtain the modified classes from the build server.

**Comment by gayanper** [comment]
This is a feature that I missed alot when debugging. One reason to go back to JDT LS builds

**Comment by gayanper** [comment]
Any plans to open source the Gradle build server code ?

**Comment by jdneo** [comment]
It will happen in this week :)

**Comment by Mike-the-one** [comment]
No updates?

**Comment by jodevan** [comment]
I miss this feature, too

**Comment by msit11125** [comment]
had same problem...

**Comment by qiaomo** [comment]
Any plans to implement this feature?

**Comment by negativems** [comment]
Need it!

**Comment by 0gon** [comment]
Need it! 2

**Comment by Danman40th** [comment]
Received

**Comment by jdneo** [comment]
Some investigation result and thoughts:

### Root cause
Since the build is delegated to the gradle, no resource change event is notified to workspace. Thus, The resource change listener in java debugger will not know which class file is updated.

### Solution
1. To solve the synchronization issue between the workspace and the file system. A `refreshLocal()` needs to be called for the build folder after gradle build finishes.
2. Debugger needs to find the main project based on the main class name in the context.
3. If the project is a gradle build server project, since auto build for Gradle build server project will not update `.class` files, we need to trigger an additional incremental build.

One thing needs to pay attention is the performance. `refreshLocal()`, `find main project based on main class name` & `delegate build to gradle` are all time consuming actions. At least, the progress reporter should be clear to tell users what's going on.
