### ISSUE TITLE
Can't show/refresh tasks

### ISSUE THREAD

**Issue by denis111** [microsoft/vscode-gradle#25]
We have a relatively big gradle project with subrojects. The extension is unable to show available tasks:
stdout maxBuffer length exceededExecuting: /home/***/***/gradlew --console plain tasks --all

**Comment by badsyntax** [comment]
Thanks for this report. My first thoughts for this are because the extension uses `child_process.exec` instead of something like `child_process.spawn` to read stdout of the gradle command. I'll add a fix soon.

**Comment by badsyntax** [comment]
I've released a fix for this with version `2.1.2`, which should be available in the next few minutes. Let me know if you still have problems.

**Comment by denis111** [comment]
Now it works. But subrojects miss the last letter in tasks list, it shows like this: "build - subprojec". Also vscode complains that plugin is slow, i think because tasks refresh takes too much time.
Would it also be possible in the future to group tasks by subpojects instead of flat list?

**Comment by badsyntax** [comment]
Thanks for the feedback.  Can you confirm you have a setup similar to https://guides.gradle.org/creating-multi-project-builds/ ? 

I have not tested this extension with sub-projects. I will do so. 

If you don't mind, can you provide me with a screenshot that shows the task name being cut off? And can you also paste here the output of `./gradlew tasks --all` and also `./gradlew model`? 

Regarding having groups, do you mean having groups in the explorer view, or in the tasks list, or both? 

Once I have better understanding of how subprojects work I will consider adding them as groups to the explorer view and tasks list.

Regarding VS Code complaining the extension is slow, yes this is recent change in version 1.40, see here: https://code.visualstudio.com/updates/v1_40#_slow-task-provider-warning Indeed this is because the gradle refresh process takes a long time (as it's running `./gradlew tasks --all`). I suggest to click on "dont warn gradle tasks" button to ignore that warning for this extension.

**Comment by badsyntax** [comment]
No need to post any screenshots or data, i've replicated this scenario now. I will fix this with issue #36

**Comment by badsyntax** [comment]
I have now opened a pull request with support for this: https://github.com/badsyntax/vscode-gradle/pull/43 
Let me know if the changes in the screenshots will work for you.
