### ISSUE TITLE
Task view randomly doesn't work

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-gradle#903]
Extension Name: vscode-gradle
Extension Version: 3.6.1
OS Version: Windows_NT x64 10.0.19043
VSCode version: 1.59.0-insider

Sometimes, when opening `Gradle` panel in the activity bar, `Gradle Tasks` view shows nothing
![task-view](https://user-images.githubusercontent.com/45906942/128131872-1c038ab6-2465-4119-950e-c3620d5405eb.png)

After refreshing, it works well.

There is another bug, might come from the same root cause, sometimes `collapse all` button is disabled by default
![task-collapse](https://user-images.githubusercontent.com/45906942/128131361-b997d915-25d5-4a7d-b812-7899c51434d7.png)
it also works after refreshing or other operations (such as run a gradle task, etc.)

**Comment by CsCherrYY** [comment]
After investigation and debugging, I think it's the root cause of this issue.

When resolving tasks, there is an async function is awaiting.
https://github.com/microsoft/vscode-gradle/blob/f5bf5f8687d07a27848b4dd2fb1c2c7f7f0c00ba/extension/src/views/gradleTasks/GradleTasksTreeDataProvider.ts#L120

When awaiting this promise, there is a `refresh` command might be triggered, which comes from https://github.com/microsoft/vscode-gradle/blob/f5bf5f8687d07a27848b4dd2fb1c2c7f7f0c00ba/extension/src/Extension.ts#L185

To describe it simply, a new `refresh` is requested during the get task process, which results in there is no items in the view. you can easily reproduce this bug if you quickly click the `Gradle` in the Activity Bar once it appeared.

@badsyntax I'm not very sure about what is `this.client.onDidConnect(() => this.refresh());` for. I just try to comment it and this issue seems not to appear again and do not break other features. Could you please give some suggestion or comment on this? Is there any side effect if we just remove this?

**Comment by badsyntax** [comment]
@CsCherrYY I've been able to replicate this behaviour. Unfortunately it looks like a race condition but it's not clear why. (FYI I have not seen this behaviour in the past, perhaps this race condition is due to a recent change in vscode.)
 
The purpose of `this.client.onDidConnect(() => this.refresh());` is to refresh the task last after the client has reconnected. A use case for this scenario is when the server gets killed unexpectedly, in which case the extension will prompt the user to restart the server, and the grpc client will re-connect, but the task list is not automatically updated, which is why we are explicitly calling refresh(). 
You can see this yourself by killing the Java server process (on macos/linux `killall java`)

This is the prompt the user will see:

<img width="817" alt="Screenshot 2021-08-12 at 08 50 54" src="https://user-images.githubusercontent.com/102141/129159040-1e358bd7-cd0a-4110-b551-e7741cc1fb5b.png">


It would good to understand why this bug occurs (it's really not clear to me) but a possible workaround is to only add this event handler after the server has stopped, possibly in this method: 

https://github.com/microsoft/vscode-gradle/blob/cd69c0c451526803b6700c13596f2f8dfb246e7e/extension/src/client/GradleClient.ts#L71-L73

(If we add it there we'll need to unsubscribe the event handler after it's called.)

I can't think of other use cases that require `this.client.onDidConnect(() => this.refresh());` so I _think_ it's safe to move that event handling to `handleServerStop`.

**Comment by badsyntax** [comment]
To clarify a bit more, if we don't want the task list updated after the server has restarted then I think it's safe to remove that line. There's also maybe a better way to handle this scenario.

**Comment by CsCherrYY** [comment]
@badsyntax Thanks a lot for the clarification! It seems a VSCode treeview issue and I just find https://github.com/microsoft/vscode/issues/129019 (though it's about a start-as-closed view, but for other start-as-open views I can sometimes reproduce it) might be related this issue, I'll keep eyes on it. From our side, we can currently have a workaround.

For the restarting server scenario, I'm wondering if the view's content would be changed after we call `this.refresh()` again. IMO the case causing "out of sync" is that the project has been changed during the client misses the connection to the server. Otherwise, the refreshing will bring the same result. Thus, I prefer to just removing it. Does this make sense?

**Comment by badsyntax** [comment]
Yes I can also replicate the treeview bug when I drag the gradle tasks view into the main file explorer view (start-as-open) and restart vscode (but as you say that issue might still be related).

> IMO the case causing "out of sync" is that the project has been changed during the client misses the connection to the server. Otherwise, the refreshing will bring the same result. Thus, I prefer to just removing it. Does this make sense?

It makes sense yes. Refreshing will bring the same result in most cases. Maybe I added it for extreme edge cases where maybe the task view was not previously rendered with anything due to a server start failure, but i can't remember and the [PR that introduced that change](https://github.com/microsoft/vscode-gradle/pull/737) doesn't describe exactly why I added it. I think it's totally fine to remove it 👍
