### ISSUE TITLE
Gradle Project view should keep project hierarchy 

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-gradle#945]
Currently our Project view is a flat view, for some hierarchical projects it might not be intuitive to the users, and it can't provide relationships among projects.

So we should support hierarchy view of projects, and offer a way to switch between the two views.

**Comment by mklueh** [comment]
I'm currently using VSCode because of a bug in IntelliJ and the Gradle experience is not great so far. 

There is no hierarchy and if you have a multi module project with nested modules of the same name, ex. infrastructure, base, etc you won't even know to which package the module/task belongs to without waiting for the tooltips.
