### ISSUE TITLE
Improve completion quality when querying maven central

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-gradle#981]
- The kind for constant proposal is not correct.
- The order of the result is weird.

![image](https://user-images.githubusercontent.com/14052197/132184696-2aa1fcf4-fa2c-4da4-9087-3a2d44e1c84a.png)

- Optimize the top 50 results list when querying maven central.
Here is the result when typing `com.`, it suggests top 50 results to me. What rule are you using to find the top 50 results?
![image](https://user-images.githubusercontent.com/14052197/132184930-ac549365-fb57-4755-bc3a-ed57bb2e09cb.png)

**Comment by CsCherrYY** [comment]
The first two points will be fixed in #985 and #986.

>   Here is the result when typing `com.`, it suggests top 50 results to me. What rule are you using to find the top 50 results?

Here we just show the default results order of `search.maven.org`. Currently I can't find a proper way in the REST API of maven central repository to show relative results if the user just types something like `org.` or `com.`. So we can (probably) only get the default results of the request. Maybe we can mark it as enhancement points and find a better way to solve it in the future?

**Comment by CsCherrYY** [comment]
#1090 will introduce the dependency candidates from both an index file and maven local repository. For the completion results, we will offer update date information to help the user distinguish the version results.
